name = "server"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
wisp = ">= 1.3.0 and < 2.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_erlang = ">= 0.32.0 and < 1.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
shared = { path = "../shared" }
envoy = ">= 1.0.2 and < 2.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
